---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myapp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/myapp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: myapp
  values:
    fullnameOverride: orange
    image:
      repository: jpetazzo/color
      tag: latest
